In [1]:
#importing libraries
import numpy as np

In [2]:
#initializing array

lst = [1,2,3,4,5,6]
arr1 = np.array(lst)
print(arr1)

[1 2 3 4 5 6]


In [3]:
#dimentions of arr1 - by default 1-D
print(arr1.ndim)

1


In [4]:
#type of the arr
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
# version of numpy
print(np.__version__)

1.21.5


In [6]:
#initializing array with tuples

arr2 = np.array((1,2,3,4,5,6,7,8))
print(arr2)

[1 2 3 4 5 6 7 8]


In [7]:
print(type(arr2))

<class 'numpy.ndarray'>


In [8]:
# 5 D array

arr2 = np.array([1,2,3,4,5,6,7,8,9,12,43,54], ndmin = 5)
print(arr2)

[[[[[ 1  2  3  4  5  6  7  8  9 12 43 54]]]]]


In [9]:
arr_ = np.array([[1,2,3], [4,5,6]], ndmin = 3)
print(arr_)
# print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]]


In [10]:
print(arr2.ndim)

5


In [11]:
# accessing 1D array using index

arr3 = np.array([43,65,23,76,98])
print(arr3[2])

23


In [12]:
arr4 = np.array([[1,2,3,4,5,6], [5,6,3,6,8]], ndmin = 2)
print(arr4.ndim)

2


C:\Users\krishna\AppData\Local\Temp\ipykernel_9892\2576381472.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array([[1,2,3,4,5,6], [5,6,3,6,8]], ndmin = 2)


In [13]:
print(arr4)

[[list([1, 2, 3, 4, 5, 6]) list([5, 6, 3, 6, 8])]]


In [14]:
# accessing elements of 2D array

arr5 = np.array([[1,2,3,4,5], [5,3,4,6,7]])
print(arr5[1, 2])

4


In [15]:
# accessing elements of 3D array

arr6 = np.array([[[1,2,3,4,5], [3,4,5,6,7]], [[4,5,6,7,8], [6,7,8,9,1]]])
print(arr6[0,1,1])

4


In [16]:
# array slicing

arr7 = np.array([1.0,2,3,4,5,6,7,8,9,0])

# arr_name[start_indes : ending index] - ending index -> exlusive
print(arr7[1:5])

[2. 3. 4. 5.]


In [17]:
type(arr7)

numpy.ndarray

In [18]:
# slicing with steps
print(arr7[0:10:3])

[1. 4. 7. 0.]


In [19]:
# datatypes of elements of array - use dtype object
print(arr7.dtype)

float64


In [20]:
arr8 = np.array(["Krishna", "Kant", "Singhal"])
print(arr8.dtype)

<U7


In [21]:
arr9 = np.array([1.3, 1.5, 6.4])
print(arr9.dtype)

float64


In [22]:
# reshaping arrays - 2D

arr10 = np.array([1,2,3,4,5,6,7,8,9,4,3,2])
# print(arr10)
arr11 = arr10.reshape(3,4)
print(arr11)

[[1 2 3 4]
 [5 6 7 8]
 [9 4 3 2]]


In [23]:
# reshaping array - 3D

arr12 = arr10.reshape(2,3,2)
print(arr12)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 4]
  [3 2]]]


In [24]:
# Reshaping arrays - 1D - use -1 as an argument

arr13 = arr12.reshape(-1)
print(arr13)

[1 2 3 4 5 6 7 8 9 4 3 2]


In [25]:
# accessing array using nditer() function

for x in np.nditer(arr12):
    print(x)

1
2
3
4
5
6
7
8
9
4
3
2


In [26]:
# concatination - adding - joining

arr14 = np.array([1,2,3])
arr15 = np.array([3,4,5])

arr16 = np.concatenate((arr14, arr15), axis = 0)
print(arr16)

[1 2 3 3 4 5]


In [27]:
arr17 = np.array([[1,2,3],[1,2,6]])
arr18 = np.array([[3,4,5],[6,8,6]])

arr19 = np.concatenate((arr17, arr18), axis = 1)
print(arr19)

[[1 2 3 3 4 5]
 [1 2 6 6 8 6]]


In [28]:
# splitting arrays - array_split()

arr20 = np.array([1,2,4,5,6,7,32,2,6])
arr21 = np.array_split(arr20, 4)
print(arr21)

[array([1, 2, 4]), array([5, 6]), array([ 7, 32]), array([2, 6])]


In [29]:
print(arr21[2])

[ 7 32]


In [30]:
# sorting the numpy array

arr22 = np.sort(arr12)

In [31]:
arr12

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 4],
        [3, 2]]])

In [32]:
arr_ = np.array_split(arr12, 2)
arr_

[array([[[1, 2],
         [3, 4],
         [5, 6]]]),
 array([[[7, 8],
         [9, 4],
         [3, 2]]])]

In [33]:
print(arr22)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [4 9]
  [2 3]]]


In [34]:
# filtering the arrays

arr23 = np.array([1,2,3,4,5,6,7,8,9,0])
x = [True, False, True, True, False, False, True, True, False, True]

arr24 = arr23[x]
print(arr24)

[1 3 4 7 8 0]


In [35]:
#import random from numpy

from numpy import random

In [36]:
# random integer

x = random.randint(100, size = 5)
x

array([69, 48, 37, 25, 44])

In [37]:
# random float -> 0 to 1

y = random.rand()
y

0.6479531441057372

In [38]:
z = random.randint(100, size = (2,3,3))
print(z)

[[[17 98 15]
  [18 59 38]
  [50  8 29]]

 [[16 56 92]
  [82 85 48]
  [41 11 47]]]


In [39]:
# choice

a = random.choice([1,2,3,4,5,6,7], size = (2,3,4))
a

array([[[3, 6, 5, 1],
        [3, 7, 3, 6],
        [1, 1, 3, 1]],

       [[3, 6, 6, 2],
        [7, 1, 2, 5],
        [5, 1, 5, 2]]])